// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int g = 0;
		int l = 0;
		while (n>0) {
			if (Math.random()>0.5) g++;
			else l++;
			n--;
		}
		System.out.println("> 0.5:  "+g+" times\n<= 0.5: "+l+" times");
		if (l > 0) {
			double ratio = g/(double)l;
			System.out.println("Ratio:  "+ratio);
		}
	}
}
